# Generated by Django 5.2.5 on 2025-08-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0017_newslettercampaign'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='jobs_emailq_status_b7b48b_idx',
            old_name='jobs_emailq_status_priority_scheduled_at_idx',
        ),
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='jobs_emailq_to_emai_d477d4_idx',
            old_name='jobs_emailq_to_email_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='jobs_emailq_created_db9449_idx',
            old_name='jobs_emailq_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='newsletterlog',
            new_name='jobs_newsle_status_c656e2_idx',
            old_name='jobs_newsle_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='newsletterlog',
            new_name='jobs_newsle_campaig_9f31fb_idx',
            old_name='jobs_newsle_campaign_status_idx',
        ),
        migrations.RenameIndex(
            model_name='newsletterlog',
            new_name='jobs_newsle_subscri_365b3e_idx',
            old_name='jobs_newsle_subscriber_status_idx',
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='html_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Basse'), (2, 'Normale'), (3, 'Haute'), (4, 'Urgente')], default=2),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='to_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject_template',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content_management.newslettercampaign'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sending', "En cours d'envoi"), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Retourné'), ('opened', 'Ouvert'), ('clicked', 'Cliqué')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content_management.newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
