# Generated by Django 5.2.5 on 2025-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Description meta'),
        ),
        migrations.AddField(
            model_name='program',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Titre meta'),
        ),
    ]
