# Generated by Django 5.2.5 on 2025-08-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_program_meta_description_program_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.category', verbose_name='Catégorie parente'),
        ),
    ]
