# Generated by Django 5.2.5 on 2025-08-14 09:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenu (Anglais)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (Anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu (Anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organisateur (Anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (Anglais)'),
        ),
    ]
