# Generated by Django 5.2.5 on 2025-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_alter_article_content_en_alter_article_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Anglais)'),
        ),
    ]
