# Generated by Django 5.2.5 on 2025-08-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_alter_category_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('color', models.CharField(default='#0d4786', max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Tag d'événement",
                'verbose_name_plural': "Tags d'événement",
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-start_time'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='events/banners/', verbose_name='Bannière'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='event',
            name='direct_link',
            field=models.URLField(blank=True, verbose_name='Lien direct'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('seminar', 'Séminaire'), ('workshop', 'Atelier'), ('symposium', 'Symposium'), ('congress', 'Congrès'), ('exhibition', 'Exposition'), ('competition', 'Concours'), ('hackathon', 'Hackathon'), ('other', 'Autre')], default='conference', max_length=50, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Gratuit'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('fr-en', 'Français/Anglais'), ('other', 'Autre')], default='fr', max_length=20, verbose_name='Langue principale'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Description meta'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Titre meta'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, verbose_name="Lien d'inscription"),
        ),
        migrations.AddField(
            model_name='event',
            name='scientific_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Domaine scientifique'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, verbose_name="Site web de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='events/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=200, verbose_name='Organisateur principal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organisateur principal (Anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('day_number', models.PositiveIntegerField(verbose_name='Numéro du jour')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre du jour')),
                ('description', models.TextField(blank=True, verbose_name='Description du jour')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='content_management.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Jour d'événement",
                'verbose_name_plural': "Jours d'événement",
                'ordering': ['date', 'day_number'],
                'unique_together': {('event', 'date', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('activity', models.CharField(max_length=200, verbose_name='Activité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('activity_type', models.CharField(choices=[('keynote', 'Conférence plénière'), ('session', 'Session'), ('workshop', 'Atelier'), ('break', 'Pause'), ('lunch', 'Déjeuner'), ('networking', 'Networking'), ('poster', 'Session poster'), ('other', 'Autre')], default='session', max_length=50, verbose_name="Type d'activité")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('event_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='content_management.eventday', verbose_name="Jour d'événement")),
            ],
            options={
                'verbose_name': "Élément d'agenda",
                'verbose_name_plural': "Éléments d'agenda",
                'ordering': ['start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EventFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('category', models.CharField(choices=[('general', 'Général'), ('registration', 'Inscription'), ('logistics', 'Logistique'), ('scientific', 'Scientifique'), ('technical', 'Technique'), ('other', 'Autre')], default='general', max_length=50, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible publiquement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content_management.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EventIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='events/intervenants/', verbose_name='Photo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre/Fonction')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('domain', models.CharField(max_length=200, verbose_name="Domaine d'expertise")),
                ('presentation', models.TextField(verbose_name='Texte de présentation')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie complète')),
                ('website', models.URLField(blank=True, verbose_name='Site web personnel')),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Profil Twitter')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenants', to='content_management.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Intervenant',
                'verbose_name_plural': 'Intervenants',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('logo', models.ImageField(upload_to='events/organizers/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name="Rôle dans l'événement")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='content_management.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Organisateur',
                'verbose_name_plural': 'Organisateurs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content_management.eventtag', verbose_name='Tags'),
        ),
    ]
