# Generated by Django 5.2.5 on 2025-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_eventtag_alter_event_options_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(default='GNF', max_length=3, verbose_name='Devise'),
        ),
    ]
