# Generated by Django 5.2.5 on 2025-08-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_alter_event_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_en',
        ),
    ]
