# Generated by Django 5.2.5 on 2025-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_remove_article_content_en_remove_article_excerpt_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='organization_type',
            field=models.CharField(choices=[('university', 'Université'), ('research_center', 'Centre de recherche'), ('company', 'Entreprise'), ('ngo', 'ONG'), ('government', 'Institution gouvernementale'), ('other', 'Autre')], default='other', max_length=50, verbose_name="Type d'organisation"),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/organizers/', verbose_name='Logo'),
        ),
    ]
