# Generated by Django 5.2.5 on 2025-08-15 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0011_eventorganizer_address_eventorganizer_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagenda',
            name='event_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='content_management.eventday', verbose_name="Jour d'événement"),
        ),
    ]
