# Generated by Django 5.2.5 on 2025-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0012_alter_eventagenda_event_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventintervenant',
            options={'ordering': ['nom'], 'verbose_name': 'Intervenant', 'verbose_name_plural': 'Intervenants'},
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='order',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='eventintervenant',
            name='title',
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='intervenants',
            field=models.ManyToManyField(blank=True, to='content_management.eventintervenant', verbose_name='Intervenants'),
        ),
        migrations.AddField(
            model_name='eventintervenant',
            name='biographie',
            field=models.TextField(default='Biographie à compléter', verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='eventintervenant',
            name='nom',
            field=models.CharField(default='Nom à compléter', max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='eventintervenant',
            name='profession',
            field=models.CharField(default='Profession à compléter', max_length=200, verbose_name='Profession/Titre'),
        ),
        migrations.AddField(
            model_name='eventintervenant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='eventintervenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='eventintervenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='intervenants/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='eventintervenant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
    ]
