# Generated by Django 5.2.5 on 2025-08-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0013_alter_eventintervenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du formulaire')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Formulaire actif')),
                ('allow_multiple_registrations', models.BooleanField(default=False, verbose_name='Autoriser plusieurs inscriptions')),
                ('max_registrations', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre maximum d'inscriptions")),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Date limite d'inscription")),
                ('send_confirmation_email', models.BooleanField(default=True, verbose_name='Envoyer un email de confirmation')),
                ('confirmation_message', models.TextField(blank=True, verbose_name='Message de confirmation')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Conditions générales')),
                ('require_terms_acceptance', models.BooleanField(default=False, verbose_name="Exiger l'acceptation des conditions")),
                ('primary_color', models.CharField(default='#667eea', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#764ba2', max_length=7, verbose_name='Couleur secondaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/forms/logos/', verbose_name='Logo du formulaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='content_management.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Formulaire d'inscription",
                'verbose_name_plural': "Formulaires d'inscription",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=50, unique=True, verbose_name="ID d'inscription")),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('waitlist', "Liste d'attente")], default='pending', max_length=20, verbose_name='Statut')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('cancelled_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='content_management.eventregistrationform', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': "Inscription à l'événement",
                'verbose_name_plural': "Inscriptions à l'événement",
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé du champ')),
                ('field_type', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('email', 'Email'), ('phone', 'Téléphone'), ('date', 'Date'), ('datetime', 'Date et heure'), ('number', 'Nombre'), ('select', 'Sélection unique'), ('multiselect', 'Sélection multiple'), ('radio', 'Boutons radio'), ('checkbox', 'Cases à cocher'), ('file', 'Fichier'), ('url', 'URL'), ('note', 'Note/Description'), ('divider', 'Séparateur')], max_length=20, verbose_name='Type de champ')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name="Texte d'aide")),
                ('help_text', models.TextField(blank=True, verbose_name="Texte d'aide détaillé")),
                ('required', models.BooleanField(default=False, verbose_name='Champ obligatoire')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longueur minimale')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longueur maximale')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur minimale')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur maximale')),
                ('has_options', models.BooleanField(default=False, verbose_name='A des options de choix')),
                ('allowed_file_types', models.CharField(blank=True, max_length=200, verbose_name='Types de fichiers autorisés')),
                ('max_file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille maximale (MB)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Champ visible')),
                ('show_when_value', models.CharField(blank=True, max_length=200, verbose_name='Afficher quand la valeur est')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='content_management.formfield', verbose_name='Dépend de')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='content_management.eventregistrationform', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': 'Champ de formulaire',
                'verbose_name_plural': 'Champs de formulaire',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name="Libellé de l'option")),
                ('value', models.CharField(max_length=200, verbose_name="Valeur de l'option")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_default', models.BooleanField(default=False, verbose_name='Option par défaut')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content_management.formfield', verbose_name='Champ')),
            ],
            options={
                'verbose_name': 'Option de champ',
                'verbose_name_plural': 'Options de champ',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, verbose_name='Valeur texte')),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur numérique')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Valeur date')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='Valeur date/heure')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Valeur booléenne')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='events/registrations/files/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.formfield', verbose_name='Champ')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='content_management.eventregistration', verbose_name='Inscription')),
                ('selected_options', models.ManyToManyField(blank=True, to='content_management.formfieldoption', verbose_name='Options sélectionnées')),
            ],
            options={
                'verbose_name': 'Réponse au formulaire',
                'verbose_name_plural': 'Réponses au formulaire',
                'unique_together': {('registration', 'field')},
            },
        ),
    ]
