# Generated by Django 5.2.5 on 2025-08-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0014_eventregistrationform_eventregistration_formfield_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partners',
        ),
        migrations.AddField(
            model_name='project',
            name='partners_text',
            field=models.TextField(blank=True, verbose_name='Partenaires (texte libre)'),
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_partners/logos/', verbose_name='Logo')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle dans le projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='content_management.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Partenaire de projet',
                'verbose_name_plural': 'Partenaires de projet',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
