# Generated by Django 5.2.5 on 2025-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0015_remove_project_partners_project_partners_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact'),
        ),
    ]
