# Generated by Django 5.2.5 on 2025-08-18 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0016_partner_contact_email_partner_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la campagne')),
                ('subject', models.CharField(max_length=200, verbose_name="Sujet de l'email")),
                ('content', models.TextField(verbose_name='Contenu de la newsletter')),
                ('template_name', models.CharField(default='newsletter_default.html', max_length=100, verbose_name='Nom du template')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sending', "En cours d'envoi"), ('completed', 'Terminée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure programmées')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'échecs")),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name="Début d'envoi")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'envoi")),
                ('target_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('all', 'Toutes')], default='all', max_length=3, verbose_name='Langue cible')),
                ('target_active_only', models.BooleanField(default=True, verbose_name='Abonnés actifs uniquement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Campagne newsletter',
                'verbose_name_plural': 'Campagnes newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
