# Generated by Django 5.2.5 on 2025-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0017_newslettercampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('management', 'Direction'), ('research', 'Recherche'), ('teaching', 'Enseignement'), ('technical', 'Technique'), ('administrative', 'Administratif'), ('communication', 'Communication'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('biography', models.TextField(verbose_name='Biographie')),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Profil Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='Chaîne YouTube')),
                ('facebook', models.URLField(blank=True, verbose_name='Profil Facebook')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
