# Generated by Django 5.2.5 on 2025-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0018_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste'),
        ),
    ]
