# Generated by Django 5.2.5 on 2025-08-26 15:03

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Génère des slugs pour les membres existants"""
    TeamMember = apps.get_model('content_management', 'TeamMember')
    for member in TeamMember.objects.all():
        base_slug = slugify(f"{member.last_name}-{member.first_name}")
        slug = base_slug
        counter = 1
        
        # Vérifier si le slug existe déjà
        while TeamMember.objects.filter(slug=slug).exclude(pk=member.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        member.slug = slug
        member.save()


def reverse_generate_slugs(apps, schema_editor):
    """Supprime les slugs (pour la migration inverse)"""
    TeamMember = apps.get_model('content_management', 'TeamMember')
    TeamMember.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0020_add_slug_field'),
    ]

    operations = [
        # Étape 1: Générer les slugs pour les enregistrements existants
        migrations.RunPython(generate_slugs, reverse_generate_slugs),
        
        # Étape 2: Rendre le champ obligatoire et unique
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
