# Generated by Django 5.2.5 on 2025-08-26 15:30

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0021_populate_slug_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#0d4786', max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Tag d'actualité",
                'verbose_name_plural': "Tags d'actualités",
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Extrait')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('deactivated', 'Désactivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_breaking_news', models.BooleanField(default=False, verbose_name='Actualité urgente')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de programmation')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('featured_image', models.ImageField(blank=True, upload_to='news/featured/', verbose_name='Image principale')),
                ('external_url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo')),
                ('audio_file', models.FileField(blank=True, upload_to='news/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Fichier audio')),
                ('document_file', models.FileField(blank=True, upload_to='news/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'])], verbose_name='Document joint')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Titre meta')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Description meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés meta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Autoriser les commentaires')),
                ('require_approval', models.BooleanField(default=False, verbose_name='Nécessite approbation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at', '-created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('author_name', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('author_email', models.EmailField(max_length=254, verbose_name="Email de l'auteur")),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Spam')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_management.news', verbose_name='Actualité')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content_management.newscomment', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': "Commentaire d'actualité",
                'verbose_name_plural': "Commentaires d'actualités",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Image principale')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='content_management.news', verbose_name='Actualité')),
            ],
            options={
                'verbose_name': "Image d'actualité",
                'verbose_name_plural': "Images d'actualités",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='news_gallery', to='content_management.newsimage', verbose_name="Galerie d'images"),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content_management.newstag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'published_at'], name='content_man_status_c38e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured', 'published_at'], name='content_man_is_feat_5da9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', 'status'], name='content_man_categor_d2f645_idx'),
        ),
    ]
