# Generated by Django 5.2.5 on 2025-08-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0022_newstag_alter_teammember_slug_news_newscomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='parent_comment',
        ),
        migrations.DeleteModel(
            name='NewsTag',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
        migrations.DeleteModel(
            name='NewsComment',
        ),
    ]
