# Generated by Django 5.2.5 on 2025-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0024_conferenceroom_externalorganization_roomimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='features',
            field=models.TextField(blank=True, help_text='Liste des équipements: projecteur, son, wifi, etc. (séparés par des virgules ou des retours à la ligne)', verbose_name='Équipements disponibles'),
        ),
    ]
