# Generated by Django 5.2.5 on 2025-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_change_features_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total'),
        ),
    ]
