# Generated by Django 5.2.5 on 2025-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0026_fix_total_price_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='attendees_count',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre estimé de participants', null=True, verbose_name='Nombre de participants'),
        ),
    ]
