# Generated by Django 5.2.5 on 2025-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0027_make_attendees_count_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommaintenance',
            name='cost',
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé'),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='medium', max_length=20, verbose_name='Priorité'),
        ),
    ]
