# Generated by Django 5.2.5 on 2025-08-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0028_remove_roommaintenance_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('personna_type', models.CharField(choices=[('journalist', 'Journaliste'), ('researcher', 'Chercheur'), ('expert', 'Expert'), ('consultant', 'Consultant'), ('academic', 'Académique'), ('professional', 'Professionnel'), ('other', 'Autre')], max_length=20, verbose_name='Type de personna')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='personnas/avatars/', verbose_name='Photo de profil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Personna',
                'verbose_name_plural': 'Personnas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/images/', verbose_name='Image principale')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de la vidéo')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('personna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='content_management.personna', verbose_name='Personna')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
