# Generated by Django 5.2.5 on 2025-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0029_personna_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personna',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='personna_type',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='website',
        ),
        migrations.RemoveField(
            model_name='personna',
            name='youtube',
        ),
        migrations.AddField(
            model_name='personna',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personna',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personna',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
