# Generated by Django 5.2.5 on 2025-08-27 21:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0030_remove_personna_avatar_remove_personna_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Résumé court du blog (max 300 caractères). Si vide, sera généré automatiquement depuis le contenu.', max_length=300, verbose_name='Extrait court'),
        ),
    ]
