# Generated by Django 5.2.5 on 2025-08-28 14:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0031_alter_blog_content_alter_blog_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Titre principal')),
                ('hero_subtitle', models.TextField(verbose_name='Sous-titre principal')),
                ('hero_background', models.ImageField(upload_to='about/hero/', verbose_name='Image de fond hero')),
                ('history_title', models.CharField(default='Notre Histoire', max_length=200, verbose_name="Titre de l'histoire")),
                ('history_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenu de l'histoire")),
                ('timeline_items', models.JSONField(default=list, help_text="Format: [{'year': '2020', 'title': 'Titre', 'description': 'Description'}]", verbose_name='Éléments de la timeline')),
                ('values_title', models.CharField(default='Nos Valeurs Fondamentales', max_length=200, verbose_name='Titre des valeurs')),
                ('values_subtitle', models.TextField(default='Les principes qui guident nos actions au quotidien', verbose_name='Sous-titre des valeurs')),
                ('team_title', models.CharField(default='Notre Équipe de Direction', max_length=200, verbose_name="Titre de l'équipe")),
                ('team_subtitle', models.TextField(default="Des experts passionnés qui dirigent la CSIG vers l'excellence", verbose_name="Sous-titre de l'équipe")),
                ('cta_title', models.CharField(default='Rejoignez la Révolution Scientifique', max_length=200, verbose_name='Titre CTA')),
                ('cta_content', models.TextField(verbose_name='Contenu CTA')),
                ('hero_stats', models.JSONField(default=list, help_text="Format: [{'number': '50+', 'label': 'Projets innovants'}]", verbose_name='Statistiques hero')),
                ('achievements', models.JSONField(default=list, help_text="Format: [{'icon': 'fas fa-trophy', 'text': 'Centre d'excellence reconnu par l'UNESCO'}]", verbose_name='Réalisations')),
                ('values_list', models.JSONField(default=list, help_text="Format: [{'icon': 'fas fa-lightbulb', 'title': 'Innovation', 'description': 'Description'}]", verbose_name='Liste des valeurs')),
                ('team_members', models.JSONField(default=list, help_text="Format: [{'name': 'Dr. Mamadou Diallo', 'position': 'Directeur Général', 'description': 'Description', 'image': 'URL image'}]", verbose_name="Membres de l'équipe")),
                ('is_active', models.BooleanField(default=True, verbose_name='Page active')),
                ('show_timeline', models.BooleanField(default=True, verbose_name='Afficher la timeline')),
                ('show_values', models.BooleanField(default=True, verbose_name='Afficher les valeurs')),
                ('show_team', models.BooleanField(default=True, verbose_name="Afficher l'équipe")),
                ('show_achievements', models.BooleanField(default=True, verbose_name='Afficher les réalisations')),
            ],
            options={
                'verbose_name': 'Page À propos',
                'verbose_name_plural': 'Pages À propos',
            },
        ),
    ]
