# Generated by Django 5.2.5 on 2025-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0032_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du quartier')),
                ('description', models.TextField(verbose_name='Description du quartier')),
                ('icon', models.CharField(help_text='Ex: fas fa-building, fas fa-flask, fas fa-microscope', max_length=100, verbose_name='Icône FontAwesome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_districts/', verbose_name='Image du quartier')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Quartier actif')),
            ],
            options={
                'verbose_name': 'Quartier de la cité',
                'verbose_name_plural': 'Quartiers de la cité',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('icon', models.CharField(help_text='Ex: fas fa-lightbulb, fas fa-heart, fas fa-star', max_length=100, verbose_name='Icône FontAwesome')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la valeur')),
                ('description', models.TextField(verbose_name='Description de la valeur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Valeur active')),
            ],
            options={
                'verbose_name': 'Valeur fondamentale',
                'verbose_name_plural': 'Valeurs fondamentales',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_team',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_timeline',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_values',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='timeline_items',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values_list',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='districts_subtitle',
            field=models.TextField(default='Découvrez les différents espaces de notre cité des sciences', verbose_name='Sous-titre des quartiers'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='districts_title',
            field=models.CharField(default='Les Quartiers de la Cité', max_length=200, verbose_name='Titre des quartiers'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_districts',
            field=models.BooleanField(default=True, verbose_name='Afficher les quartiers'),
        ),
    ]
