# Generated by Django 5.2.5 on 2025-08-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0033_citydistrict_corevalue_remove_aboutpage_show_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_stats',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_achievements',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_content',
            field=models.TextField(verbose_name='Contenu de la section CTA'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('icon', models.CharField(help_text='Ex: fas fa-trophy, fas fa-medal, fas fa-star', max_length=100, verbose_name='Icône FontAwesome')),
                ('text', models.TextField(verbose_name='Description de la réalisation')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Réalisation active')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='content_management.aboutpage')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='HeroStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('number', models.CharField(max_length=50, verbose_name='Nombre/Chiffre')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Statistique active')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_statistics', to='content_management.aboutpage')),
            ],
            options={
                'verbose_name': 'Statistique hero',
                'verbose_name_plural': 'Statistiques hero',
                'ordering': ['order', 'number'],
            },
        ),
    ]
